"""
Curated knowledge base seed data.

These entries are written in good faith based on general, well-known
Indian legal principles for demo/educational purposes. They are NOT a
substitute for professional legal advice — the app itself displays a
disclaimer to this effect (see frontend).
"""

SEED_ENTRIES = [
    {
        "situation": "Can a police officer check my phone without permission?",
        "category": "police",
        "verdict": "conditional",
        "simple_explanation": "Generally no — police need either your consent, a warrant, or a valid legal reason (like a lawful arrest or active investigation) to search your phone.",
        "legal_explanation": "Under the Bharatiya Nagarik Suraksha Sanhita (BNSS) 2023 (replacing CrPC), search and seizure of personal property including electronic devices requires due process — typically a warrant under search provisions, or it must fall under recognized exceptions like search incident to a lawful arrest.",
        "law_reference": "BNSS 2023, Sections on Search & Seizure (corresponding to former CrPC Sections 91, 100, 165); Information Technology Act, 2000",
        "your_rights": "You have the right to ask the officer for identification and the reason for the search. You can ask whether they have a warrant. You are not legally obligated to unlock your phone without due process, though refusal in some contexts may itself raise suspicion.",
        "exceptions": "If you are under lawful arrest, or in specific situations like airport security/customs checks, or if a magistrate has issued a search warrant, the rules differ.",
        "what_to_do_next": "Politely ask for the officer's name, badge number, and reason. Note the time, place, and station. If you believe the search was unlawful, you can file a complaint with the Superintendent of Police or approach the State Human Rights Commission.",
        "keywords": "phone search privacy mobile device police check seizure",
        "tourist_relevant": True,
    },
    {
        "situation": "Can my landlord enter my rented house without notice?",
        "category": "tenant",
        "verdict": "illegal",
        "simple_explanation": "No — a landlord generally cannot enter your rented home without prior notice except in genuine emergencies.",
        "legal_explanation": "Most State Rent Control Acts and the Model Tenancy Act, 2021 require landlords to provide reasonable prior notice (commonly 24 hours) before entering a tenant's premises for inspection or repairs, except in emergencies like fire or major water leakage.",
        "law_reference": "Model Tenancy Act, 2021, Section 18; respective State Rent Control Acts",
        "your_rights": "You have the right to peaceful possession and privacy in your rented home for the duration of a valid tenancy agreement. Entry for repairs/inspection should be at a mutually convenient, pre-notified time.",
        "exceptions": "Genuine emergencies (fire, gas leak, structural danger) may justify immediate entry. If your rental agreement specifies different notice terms, those terms (if lawful) may apply.",
        "what_to_do_next": "Communicate in writing (SMS/email/WhatsApp) reminding the landlord of notice requirements. Keep records of any unauthorized entry. Persistent violations can be raised with the local Rent Authority or via a civil suit for breach of quiet enjoyment.",
        "keywords": "landlord rent tenant privacy entry notice eviction rental agreement",
        "tourist_relevant": False,
    },
    {
        "situation": "Can a shop refuse to give me a bill or receipt?",
        "category": "consumer",
        "verdict": "illegal",
        "simple_explanation": "No — every business is legally required to give you a proper bill for goods or services purchased.",
        "legal_explanation": "Under GST rules, registered businesses above the threshold must issue a tax invoice for every sale. Refusing to give a bill is both a consumer rights violation and a tax compliance violation.",
        "law_reference": "Consumer Protection Act, 2019; Central Goods and Services Tax (CGST) Act, 2017, Section 31",
        "your_rights": "You have the right to demand a bill/invoice for any purchase. This protects you in case of defective goods, warranty claims, or price disputes.",
        "exceptions": "Very small unregistered vendors below the GST threshold may not issue formal GST invoices, but should still provide a basic receipt on request.",
        "what_to_do_next": "Insist politely on a bill before paying. If refused, you can report the shop to the local GST department or file a complaint on the National Consumer Helpline (1915) or via the e-daakhil consumer portal.",
        "keywords": "bill receipt invoice shop gst consumer rights purchase",
        "tourist_relevant": True,
    },
    {
        "situation": "Is it legal to fly a drone in my area?",
        "category": "property",
        "verdict": "conditional",
        "simple_explanation": "It depends — drone flying is legal in India but is regulated based on drone weight, altitude, and zone (some areas like airports and government buildings are no-fly zones).",
        "legal_explanation": "The Drone Rules, 2021 (issued under the Aircraft Act, 1934) require registration of most drones via the Digital Sky Platform, and flying is restricted in red zones (e.g., near airports, international borders, military installations) and requires permission in yellow zones.",
        "law_reference": "Drone Rules, 2021; Aircraft Act, 1934",
        "your_rights": "You may fly nano drones (under 250g) for recreational use in green zones without prior permission in most cases.",
        "exceptions": "Flying near airports, defense areas, state borders, or during VIP movement/security events is restricted or banned regardless of drone size.",
        "what_to_do_next": "Check your zone classification on the Digital Sky platform before flying. Register your drone if required. Avoid flying near airports, government buildings, or large public gatherings.",
        "keywords": "drone fly aircraft airspace digital sky permission",
        "tourist_relevant": True,
    },
    {
        "situation": "A taxi or auto driver is charging me much more than the meter fare. Is this legal?",
        "category": "tourist",
        "verdict": "illegal",
        "simple_explanation": "No — drivers must charge according to the government-fixed meter rate or pre-agreed app fare; overcharging is a punishable offence.",
        "legal_explanation": "State Motor Vehicles Rules and city-specific taxi/auto regulations mandate metered fares (or app-displayed fares for aggregators). Charging beyond this without consent is an offence under the Motor Vehicles Act framework and local transport regulations.",
        "law_reference": "Motor Vehicles Act, 1988 (as amended 2019); State Taxi/Auto Rickshaw Rules",
        "your_rights": "You have the right to pay only the metered or pre-agreed fare. You can ask the driver to reset/show the meter, or rely on the fare locked in your ride-hailing app.",
        "exceptions": "Pre-negotiated fares for outstation/full-day hire, night surcharges, or toll/parking charges (if applicable and disclosed) are legitimate add-ons.",
        "what_to_do_next": "Note the vehicle number and driver details. Report to local traffic police, the city transport helpline, or use the in-app 'report issue' feature for aggregator rides. Many cities have dedicated traffic helpline numbers (e.g., 103).",
        "keywords": "taxi auto overcharge fare meter cab tourist scam",
        "tourist_relevant": True,
    },
    {
        "situation": "Can a hotel keep my passport during my stay?",
        "category": "tourist",
        "verdict": "conditional",
        "simple_explanation": "Hotels can ask to see and copy your passport for registration purposes, but they generally should not retain your original passport for your entire stay without valid reason.",
        "legal_explanation": "Under the Registration of Foreigners Rules and state police regulations, hotels are required to record foreign guest details (often via a 'C-Form') typically within 24 hours of check-in, which usually requires only a copy, not indefinite custody of the original document.",
        "law_reference": "Registration of Foreigners Rules, 1992; Foreigners Act, 1946; State Police Lodging House Rules",
        "your_rights": "You have the right to retain your original passport. You can offer a photocopy or allow the hotel to photograph/scan it for their records.",
        "exceptions": "Some hotels may briefly hold the passport only for the time needed to complete C-Form registration, and should return it promptly after.",
        "what_to_do_next": "Politely ask for your passport back after the hotel completes its copy/registration. If a hotel insists on retaining it long-term, you can contact the local Foreigners Regional Registration Office (FRRO) or your country's embassy/consulate for guidance.",
        "keywords": "passport hotel foreigner tourist registration c-form",
        "tourist_relevant": True,
    },
    {
        "situation": "Can someone be arrested immediately without any warrant?",
        "category": "police",
        "verdict": "conditional",
        "simple_explanation": "Sometimes — police can arrest without a warrant only in specific situations, like being caught committing a serious (cognizable) offence; otherwise an arrest generally needs a warrant or magistrate's order.",
        "legal_explanation": "Under the BNSS 2023 (replacing CrPC), police have powers of arrest without warrant for cognizable offences (serious crimes) under specified conditions, but for non-cognizable offences a warrant or magistrate's permission is generally required.",
        "law_reference": "BNSS 2023, provisions on Arrest (corresponding to former CrPC Sections 41, 41A, 151)",
        "your_rights": "You have the right to know the grounds of arrest, the right to inform a relative/friend, the right to legal counsel, and the right to be produced before a magistrate within 24 hours (excluding travel time).",
        "exceptions": "Cognizable offences (e.g., serious crimes like assault, theft caught in the act) allow warrantless arrest. Non-cognizable offences typically require a warrant.",
        "what_to_do_next": "Calmly ask for the reason for arrest and the officer's identification. Request to inform a family member or lawyer. Note the time and location. You can later consult a lawyer about the legality of the arrest procedure followed.",
        "keywords": "arrest warrant police custody rights cognizable",
        "tourist_relevant": True,
    },
    {
        "situation": "I received an OTP fraud call and lost money from my bank account. What can I do?",
        "category": "cybercrime",
        "verdict": "illegal",
        "simple_explanation": "What happened to you is a cybercrime/financial fraud, and you should report it immediately — there are time-sensitive steps that can help recover funds.",
        "legal_explanation": "OTP/phishing fraud falls under the Information Technology Act, 2000 (Sections on cyber fraud and identity theft) as well as provisions of the Bharatiya Nyaya Sanhita (BNS) 2023 dealing with cheating and criminal breach of trust.",
        "law_reference": "Information Technology Act, 2000, Sections 66C & 66D; Bharatiya Nyaya Sanhita (BNS) 2023, cheating provisions",
        "your_rights": "You have the right to file a complaint, request your bank to freeze/trace the transaction, and seek redress through banking ombudsman channels if your bank is unresponsive.",
        "exceptions": "If you voluntarily shared the OTP without any deception involved, banks may treat liability differently — quick reporting strengthens your claim regardless.",
        "what_to_do_next": "Immediately call the National Cybercrime Helpline 1930, file a complaint at cybercrime.gov.in, and inform your bank to block further transactions. The first few hours are critical for fund recovery.",
        "keywords": "otp fraud cybercrime bank scam phishing money stolen online",
        "tourist_relevant": True,
    },
    {
        "situation": "Is it legal to record a conversation with someone without telling them?",
        "category": "cybercrime",
        "verdict": "conditional",
        "simple_explanation": "Recording your own conversation (where you're a participant) is generally legal in India, but secretly recording others without consent, or sharing/publishing it, can raise privacy and legal issues.",
        "legal_explanation": "Indian law does not have a single blanket 'two-party consent' rule like some countries, but the right to privacy is a recognized fundamental right (K.S. Puttaswamy judgment), and unauthorized recording in private spaces, or misuse of recordings, can attract liability under privacy and IT laws.",
        "law_reference": "Right to Privacy (Article 21, per K.S. Puttaswamy v. Union of India, 2017); Information Technology Act, 2000",
        "your_rights": "You can generally record calls/conversations you're personally part of for personal record-keeping.",
        "exceptions": "Recording someone in a place with a reasonable expectation of privacy (like a private bathroom or bedroom) without consent, or publishing/sharing a recording to harass or defame, is legally risky.",
        "what_to_do_next": "If recording for evidence (e.g., harassment, fraud), keep it for personal/legal use rather than public posting, and consult a lawyer before using it in any legal proceeding.",
        "keywords": "recording conversation call privacy consent surveillance",
        "tourist_relevant": False,
    },
    {
        "situation": "Can my employer fire me without any notice or reason?",
        "category": "property",
        "verdict": "conditional",
        "simple_explanation": "Usually no — most employees are entitled to a notice period or compensation in lieu of notice, as defined in their employment contract or applicable labour law, unless dismissed for proven misconduct.",
        "legal_explanation": "For employees covered under the Industrial Disputes Act, 1947 (workmen) or Shops & Establishments Acts, there are mandated notice periods and procedures for termination, except in cases of proven misconduct following due inquiry.",
        "law_reference": "Industrial Disputes Act, 1947; State Shops and Establishments Acts; individual Employment Contract terms",
        "your_rights": "You have the right to notice (or pay in lieu), and in cases of misconduct allegations, the right to a fair inquiry before termination.",
        "exceptions": "Probationary employees, contractual staff, and senior managerial roles outside 'workman' definitions may have different (often contract-governed) termination terms.",
        "what_to_do_next": "Review your appointment letter/contract for the notice clause. If you believe termination was unfair, you can raise it with the labour commissioner's office or consult an employment lawyer.",
        "keywords": "employer fired termination notice job labour employment",
        "tourist_relevant": False,
    },
    {
        "situation": "What should I do immediately after a road accident in India?",
        "category": "police",
        "verdict": "conditional",
        "simple_explanation": "Stay calm, ensure safety, inform the police, and avoid admitting fault on the spot — there are specific legal steps that protect you.",
        "legal_explanation": "Under the Motor Vehicles Act, 1988, all road accidents involving injury or significant damage must be reported to the nearest police station, and an FIR/accident report is typically required for insurance claims.",
        "law_reference": "Motor Vehicles Act, 1988; BNSS 2023 provisions on FIR registration",
        "your_rights": "You have the right to call the police and ambulance (call 112 for unified emergency services), the right to request medical aid for any injured party (Good Samaritan protections exist for helpers), and the right to have an accurate accident report filed.",
        "exceptions": "Minor fender-benders with no injury and mutual agreement may sometimes be resolved without police involvement, though documenting it (photos, witness info) is still wise.",
        "what_to_do_next": "Call 112 (emergency) immediately if there are injuries. Take photos of the scene, vehicles, and number plates. Exchange contact and insurance details. File a police report/FIR, especially if you plan to claim insurance.",
        "keywords": "accident road crash fir insurance police emergency",
        "tourist_relevant": True,
    },
    {
        "situation": "Can I be stopped and questioned by police just for walking at night?",
        "category": "police",
        "verdict": "conditional",
        "simple_explanation": "Police can stop and ask questions as part of routine patrol/verification, but they generally cannot detain or search you without valid suspicion or legal grounds.",
        "legal_explanation": "Police have general powers to question individuals as part of preventive policing, especially in sensitive areas or during specific law-and-order situations, but prolonged detention requires following due arrest/detention procedures under BNSS 2023.",
        "law_reference": "BNSS 2023 provisions on police powers and preventive action (corresponding to former CrPC Sections 41, 151)",
        "your_rights": "You have the right to ask why you're being stopped, to see the officer's identification, and to not be detained beyond a brief, reasonable questioning without formal arrest procedure.",
        "exceptions": "During curfews, prohibitory orders (like Section 163 BNSS, formerly Section 144 CrPC), or specific security alerts, broader stop-and-question powers may apply.",
        "what_to_do_next": "Stay calm and cooperative, answer basic identification questions, and politely ask for the reason if questioning continues. Note officer details if you feel the stop was unjustified.",
        "keywords": "police stop question night walking detain id check",
        "tourist_relevant": True,
    },
]
